# The coordinates for all target locations were extracted directly from the PyRoboSim world layout to match the same map structure
# locations:
Dining:
  frame_id: map
  pose:
    x: 0.0
    y: 0.0
    z: 0.0
    yaw_deg: 0

Kitchen:
  frame_id: map
  pose:
    x: -2.94
    y: -1.75
    z: 0.0
    yaw_deg: 0

Trash:
  frame_id: map
  pose:
    x: -1.70
    y: -5.5
    z: 0.0
    yaw_deg: 90

Closet:
  frame_id: map
  pose:
    x: -8.5
    y: 7.0
    z: 0.0
    yaw_deg: 180

Office:
  frame_id: map
  pose:
    x: -8.25
    y: -7.0
    z: 0.0
    yaw_deg: 180
