# This is just an example of a YAML file defining locations in a map for a robot.
Kitchen:
  frame_id: map
  target_goal:
    x: 9.0
    y: 6.0
    yaw: 30 # degrees

Office:
  frame_id: map
  target_goal:
    x: 4.0
    y: 5.0
    yaw: 90 # degrees
