name: ROS2 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: "ubuntu:24.04"
            ros-distro: "rolling"
    container:
      image: ${{ matrix.docker-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}
      - name: Build and Test
        run: .github/actions/build-and-test.sh
        env:
          DOCKER_IMAGE: ${{ matrix.docker-image }}
          ROS_DISTRO: ${{ matrix.ros-distro }}
