name: ROS2 CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: build-and-test-against-${{ matrix.ros-distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: "ubuntu:24.04"
            ros-distro: "rolling"
          - docker-image: "ubuntu:24.04"
            ros-distro: "kilted"
          - docker-image: "ubuntu:24.04"
            ros-distro: "jazzy"
    container:
      image: ${{ matrix.docker-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}

      - name: Prepare third-party dependencies
        run: sed "s/\$ROS_DISTRO/${ROS_DISTRO}/g" ThirdParty.template.repos > dependencies.repos
        env:
          ROS_DISTRO: ${{ matrix.ros-distro }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          target-ros2-distro: ${{ matrix.ros-distro }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependencies.repos
          skip-tests: true
